const INSTALLMENT_TYPES = {
  DEPOSIT: 'DEPOSIT',
  PAYMENT: 'PAYMENT'
}

const INSTALLMENT_STATUS = {
  PAID: 'PAID',
  MORE_PAID: 'MORE_PAID',
  UN_PAID: 'UN_PAID',
  LATE_FEES: 'LATE_FEES',
  SUSPENDED_FEES: 'SUSPENDED_FEES'
}

module.exports = {
  INSTALLMENT_TYPES,
  INSTALLMENT_STATUS
}
