const INSTALLMENT_TYPES = {
  DEPOSIT: 'DEPOSIT',
  PAYMENT: 'PAYMENT'
}

const INSTALLMENT_STATUS = {
  PAID: 'PAID',
  UN_PAID: 'UN_PAID',
  LESS_PAID: 'LESS_PAID'
}

const PAYMENT_METHODS = {
  CASH: 'CASH',
  CREDIT: 'CREDIT',
  MONEY_ORDER: 'MONEY_ORDER',
  CHECK: 'CHECK'
}

module.exports = {
  INSTALLMENT_TYPES,
  INSTALLMENT_STATUS,
  PAYMENT_METHODS
}
