const HR_TASK_TYPES = {
  MENTAL: 'MENTAL',
  ABSENT: 'ABSENT',
  OTHERS: 'OTHERS',
  VACATION: 'VOCATION'
}

const HR_LOGIN_CONDITIONS = {
  EXCELLENT_TRACKING: 'EXCELLENT_TRACKING',
  GOOD_TRACKING: 'GOOD_TRACKING',
  NORMAL_TRACKING: 'NORMAL_TRACKING',
  POOR_TRACKING: 'POOR_TRACKING',
  ALL: 'ALL'
}

module.exports = { HR_TASK_TYPES, HR_LOGIN_CONDITIONS }
