export { default as UserModalSalarySettingsTab } from './UserModalSalarySettingsTab'
export { default as UserModalWorkingScheduleSettingsTab } from './UserModalWorkingScheduleSettingsTab'
export { default as UserModalWorkingScheduleSettingsSummaryBody } from './UserModalWorkingScheduleSettingsSummaryBody'
export { default as UserModalWorkingScheduleSettingsSummaryFooter } from './UserModalWorkingScheduleSettingsSummaryFooter'
export { default as UserModalSalarySettingsSummaryFooter } from './UserModalSalarySettingsSummaryFooter'
export { default as UserModalSalarySettingsSummaryBody } from './UserModalSalarySettingsSummaryBody'
export { default as UserModalHrSettingsTab } from './UserModalHrSettingsTab'
