const HR_LOGIN_CONDITIONS = {
  EXCELLENT_TRACKING: 'EXCELLENT_TRACKING',
  GOOD_TRACKING: 'GOOD_TRACKING',
  NORMAL_TRACKING: 'NORMAL_TRACKING',
  POOR_TRACKING: 'POOR_TRACKING',
  ALL: 'ALL'
}

const HR_LOGIN_CONDITIONS_OPTIONS = [
  { value: HR_LOGIN_CONDITIONS.EXCELLENT_TRACKING, label: 'Excellent' },
  { value: HR_LOGIN_CONDITIONS.GOOD_TRACKING, label: 'Good' },
  { value: HR_LOGIN_CONDITIONS.NORMAL_TRACKING, label: 'Normal' },
  { value: HR_LOGIN_CONDITIONS.POOR_TRACKING, label: 'Poor' },
  { value: HR_LOGIN_CONDITIONS.ALL, label: 'All' }
]

export { HR_LOGIN_CONDITIONS, HR_LOGIN_CONDITIONS_OPTIONS }
