const HR_LOGIN_CONDITIONS = {
  ALL: 'ALL',
  EXCELLENT_TRACKING: 'EXCELLENT_TRACKING',
  GOOD_TRACKING: 'GOOD_TRACKING',
  NORMAL_TRACKING: 'NORMAL_TRACKING',
  POOR_TRACKING: 'POOR_TRACKING'
}

const HR_LOGIN_CONDITIONS_COLOR = {
  [HR_LOGIN_CONDITIONS.EXCELLENT_TRACKING]: { name: 'success', hexCode: '#17C964' },
  [HR_LOGIN_CONDITIONS.GOOD_TRACKING]: { name: 'primary', hexCode: '#0072F5' },
  [HR_LOGIN_CONDITIONS.NORMAL_TRACKING]: { name: 'warning', hexCode: '#F5A524' },
  [HR_LOGIN_CONDITIONS.POOR_TRACKING]: { name: 'error', hexCode: '#F31260' }
}

const HR_LOGIN_CONDITIONS_OPTIONS = [
  { value: HR_LOGIN_CONDITIONS.EXCELLENT_TRACKING, label: 'Excellent' },
  { value: HR_LOGIN_CONDITIONS.GOOD_TRACKING, label: 'Good' },
  { value: HR_LOGIN_CONDITIONS.NORMAL_TRACKING, label: 'Normal' },
  { value: HR_LOGIN_CONDITIONS.POOR_TRACKING, label: 'Poor' },
  { value: HR_LOGIN_CONDITIONS.ALL, label: 'All' }
]

export { HR_LOGIN_CONDITIONS, HR_LOGIN_CONDITIONS_OPTIONS, HR_LOGIN_CONDITIONS_COLOR }
