const HR_LOGIN_CONDITIONS = {
  GOOD_TRACKING: 'GOOD_TRACKING',
  POOR_TRACKING: 'POOR_TRACKING',
  ALL: 'ALL'
}

const HR_LOGIN_CONDITIONS_OPTIONS = [
  { value: HR_LOGIN_CONDITIONS.ALL, label: 'All' },
  { value: HR_LOGIN_CONDITIONS.GOOD_TRACKING, label: 'Good Tracking' },
  { value: HR_LOGIN_CONDITIONS.POOR_TRACKING, label: 'Poor Tracking' }
]

export { HR_LOGIN_CONDITIONS, HR_LOGIN_CONDITIONS_OPTIONS }
