const HR_TASK_TYPES = {
  MENTAL: 'MENTAL',
  ABSENT: 'ABSENT',
  OTHERS: 'OTHERS',
  VACATION: 'VOCATION'
}

const HR_TASK_TYPE_COLORS = {
  [HR_TASK_TYPES.MENTAL]: '#3b4b8d',
  [HR_TASK_TYPES.ABSENT]: '#ca5b5b',
  [HR_TASK_TYPES.OTHERS]: '#ccc',
  [HR_TASK_TYPES.VACATION]: '#416fc7'
}

export { HR_TASK_TYPES, HR_TASK_TYPE_COLORS }
