export type { default as ICustomer } from './ICustomer'
export type { default as ICustomerCreateDTO } from './ICustomerCreateDTO'
export type { default as ICustomerUpdateDTO } from './ICustomerUpdateDTO'
export type { default as ICustomerAddNew } from './ICustomerAddNew'
export type { default as IReliableCustomer } from './IReliableCustomer'
