export { default as CustomerSettings } from './CustomerSettings'
export * from './reffered-by-tab'
export * from './client-type-tab'
export * from './relation-types-tab'
export * from './locations-tab'
