export { default as CompanyVariables } from './CompanyVariables'
export * from './reffered-by-tab'
export * from './relation-types-tab'
export * from './locations-tab'
export * from './customer-type-tab'
